# Generated by Django 3.2.3 on 2021-05-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(verbose_name='Текст новости'),
        ),
    ]
